### ISSUE TITLE
Missing sfx.asm and sound2.asm

### ISSUE THREAD

**Issue by lmorchard** [gauze/spudster#1]
Hi there! Just starting out in Vectrex homebrew, so I was peeking at your project for some example material. 

I cloned the repo and tried building, but it looks like sfx.asm and sound2.asm are missing. Maybe these are commonly known libraries, but I'm a noob and can't find them. Might be worth adding them to your project! 

Thanks for sharing this on github!

**Comment by gauze** [comment]
I just hadn't synced up in a while. You'd do a lot better looking at Chris Tumber's tutorial on Vectrex programming for the record.
